PAIRS = [
    ("hi", "hello how can i help you today"),
    ("hello", "hi there how can i assist you"),
    ("hey", "hey how can i help you"),
    ("how are you", "i am doing great thanks for asking"),
    ("what is your name", "i am helpdesk ai your virtual assistant"),
    ("thank you", "you are welcome happy to help"),
    ("thanks", "no problem glad i could help"),
    ("bye", "goodbye have a great day"),
    ("i need help", "sure please tell me what issue you are facing"),
    ("how do i reset my password", "go to settings then security and click reset password"),
    ("i forgot my password", "you can reset it using the forgot password link on login page"),
    ("how do i cancel my subscription", "go to billing settings and click cancel subscription"),
    ("how do i upgrade my plan", "go to billing settings and select upgrade plan"),
    ("what payment methods do you accept", "we accept credit cards debit cards and paypal"),
    ("how do i get a refund", "please contact billing support to request a refund"),
    ("my payment failed", "please check your card details and try again or use another card"),
    ("how do i delete my account", "go to account settings and click delete account"),
    ("how do i log in", "enter your email and password on the login page"),
    ("i cant log in", "please check your credentials or reset your password"),
    ("the app is not working", "please try restarting the app or reinstalling it"),
    ("how do i report a bug", "you can report bugs using the feedback form in settings"),
    ("where can i find my invoices", "go to billing history to view and download invoices"),
    ("do you offer a free trial", "yes we offer a 14 day free trial for new users"),
    ("is my data secure", "yes we use encryption to keep your data safe and secure"),
    ("can i use this on mobile", "yes our app is available on both android and ios"),
    ("good morning", "good morning how can i help you today"),
    ("good night", "good night have a wonderful rest"),
    ("are you a robot", "yes i am an ai chatbot built to help answer your questions"),
    ("what can you do", "i can help you with account billing and technical questions"),
    ("i want to speak to a human", "sure connecting you to a human agent now"),
]
